;;; Custom --- Settings
;;; Commentary:
;;; Code:
;;;disable backup
(setq backup-inhibited t)
;;;disable auto save
(setq auto-save-default nil)
(global-linum-mode 't)
(menu-bar-mode 't)
(setq prelude-whitespace nil)
(setq prelude-guru nil)
(setq flx-ido-threshhold 1000)
(global-set-key [f8] 'neotree-toggle)
(global-set-key (kbd "C-x ,") 'buffer-menu)
(global-set-key (kbd "C-c w") 'ace-window)
(require 'ggtags)
(add-hook 'c-mode-common-hook
          (lambda ()
            (when (derived-mode-p 'c-mode 'c++-mode 'java-mode 'asm-mode)
              (ggtags-mode 1))))
(define-key ggtags-mode-map (kbd "C-c g s") 'ggtags-find-other-symbol)
(define-key ggtags-mode-map (kbd "C-c g h") 'ggtags-view-tag-history)
(define-key ggtags-mode-map (kbd "C-c g r") 'ggtags-find-reference)
(define-key ggtags-mode-map (kbd "C-c g f") 'ggtags-find-file)
(define-key ggtags-mode-map (kbd "C-c g c") 'ggtags-create-tags)
(define-key ggtags-mode-map (kbd "C-c g u") 'ggtags-update-tags)
(define-key ggtags-mode-map (kbd "M-,") 'pop-tag-mark)
(setq-local imenu-create-index-function #'ggtags-build-imenu-index)
(setq speedbar-show-unknown-files t)
(require 'company)
(add-hook 'after-init-hook 'global-company-mode)
(add-to-list 'company-backends 'company-c-headers)
(add-to-list 'company-c-headers-path-system "/usr/include/c++/4.8.5/")
(require 'cc-mode)
(require 'semantic)
(global-semanticdb-minor-mode 1)
(global-semantic-idle-scheduler-mode 1)
(semantic-mode 1)
(semantic-add-system-include "/usr/include/c++/4.8.5" 'c++-mode)
(semantic-add-system-include "/usr/include/linux")
(global-semantic-idle-summary-mode 1)
(add-to-list 'semantic-default-submodes 'global-semantic-stickyfunc-mode)
(setq-local eldoc-documentation-function #'ggtags-eldoc-function)
(setq c-default-style "linux")
(provide 'custom)
;;; Custom ends here
